----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content layer - IPA - Cap Floor
This notebook demonstrates how to use Cap Floor pricing analytics.

#### Learn more

To learn more about the LSEG Data Library for Python please join the LSEG Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the LSEG Developer Community portal you will have free access to a number of learning materials 
 on the [LSEG Developer Portal](https://developers.lseg.com/en)

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [LSEG Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The LSEG Developer Community will be happy to help.

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the LSEG Data Library in the _lseg-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

## Some Imports to start with

In [2]:
import lseg.data as ld
from lseg.data.content.ipa.financial_contracts import cap_floor

## Open the data session

The open_session() function creates and open sessions based on the information contained in the lseg-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [21]:
ld.open_session()

## Retrieve data

### Single

In [22]:
response = cap_floor.Definition(
    notional_ccy="EUR",
    start_date="2022-02-11",
    amortization_schedule=[
        cap_floor.AmortizationItem(
            start_date="2025-02-12",
            end_date="2025-02-12",
            amount=100000,
            amortization_type=cap_floor.AmortizationType.SCHEDULE,
        ),
        cap_floor.AmortizationItem(
            start_date="2025-02-11",
            end_date="2025-02-11",
            amount=-100000,
            amortization_type=cap_floor.AmortizationType.SCHEDULE,
        ),
    ],
    tenor="5Y",
    buy_sell="Sell",
    notional_amount=10000000,
    interest_payment_frequency=cap_floor.Frequency.MONTHLY,
    cap_strike_percent=1,

).get_data()

response.data.df

,InstrumentTag,InstrumentDescription,ValuationDate,MarketDataDate,StartDate,EndDate,Tenor,InterestPaymentFrequency,IndexResetFrequency,IndexResetType,...,ImpliedVolatilityBp,DeltaPercent,ForwardDeltaPercent,DV01AmountInDealCcy,GammaAmountInDealCcy,VegaAmountInDealCcy,ThetaAmountInDealCcy,ErrorCode,ErrorMessage,ProcessingInformation
0,<NA>,SHORT EUR 1.0000% CAP,2024-06-13,2024-06-13,2022-02-11,2027-02-11,5Y,Monthly,Monthly,InAdvance,...,95.782875,-0.894216,-0.934072,-2190.34717,-1.302572,-385.267036,108.703687,,,"IndexName was not provided, will use index 'E..."

### Fields selection

In [23]:
response = cap_floor.Definition(
    notional_ccy="EUR",
    start_date="2022-02-11",
    amortization_schedule=[
        cap_floor.AmortizationItem(
            start_date="2025-02-12",
            end_date="2025-02-12",
            amount=100000,
            amortization_type=cap_floor.AmortizationType.SCHEDULE,
        ),
        cap_floor.AmortizationItem(
            start_date="2025-02-11",
            end_date="2025-02-11",
            amount=-100000,
            amortization_type=cap_floor.AmortizationType.SCHEDULE,
        ),
    ],
    tenor="5Y",
    buy_sell="Sell",
    notional_amount=10000000,
    interest_payment_frequency=cap_floor.Frequency.MONTHLY,
    cap_strike_percent=1,

    fields=[
        "InstrumentTag",
        "InstrumentDescription",
        "FixedRate",
        "MarketValueInDealCcy",
        "MarketValueInReportCcy",
        "ErrorMessage"
    ]
).get_data()

response.data.df

,InstrumentTag,InstrumentDescription,FixedRate,MarketValueInDealCcy,MarketValueInReportCcy,ErrorMessage
0,<NA>,SHORT EUR 1.0000% CAP,<NA>,-516753.583394,<NA>,

### Pricing parameters

In [24]:
response = cap_floor.Definition(
    notional_ccy="EUR",
    start_date="2022-02-11",
    amortization_schedule=[
        cap_floor.AmortizationItem(
            start_date="2025-02-12",
            end_date="2025-02-12",
            amount=100000,
            amortization_type=cap_floor.AmortizationType.SCHEDULE,
        ),
        cap_floor.AmortizationItem(
            start_date="2025-02-11",
            end_date="2025-02-11",
            amount=-100000,
            amortization_type=cap_floor.AmortizationType.SCHEDULE,
        ),
    ],
    tenor="5Y",
    buy_sell="Sell",
    notional_amount=10000000,
    interest_payment_frequency=cap_floor.Frequency.MONTHLY,
    cap_strike_percent=1,
    pricing_parameters=cap_floor.PricingParameters(
        skip_first_cap_floorlet=True,
        valuation_date="2020-02-07"
    )
).get_data()

response.data.df

,InstrumentTag,InstrumentDescription,ValuationDate,MarketDataDate,StartDate,EndDate,Tenor,InterestPaymentFrequency,IndexResetFrequency,IndexResetType,...,ImpliedVolatilityBp,DeltaPercent,ForwardDeltaPercent,DV01AmountInDealCcy,GammaAmountInDealCcy,VegaAmountInDealCcy,ThetaAmountInDealCcy,ErrorCode,ErrorMessage,ProcessingInformation
0,<NA>,SHORT EUR 1.0000% CAP,2020-02-07,2020-02-07,2022-02-11,2027-02-11,5Y,Monthly,Monthly,InAdvance,...,53.512249,-0.144366,-0.141734,-688.286023,-8.325092,-2397.795335,30.713049,,,"IndexName was not provided, will use index 'E..."

## Close the session

In [19]:
ld.close_session()