# LD Lib. Python Tutorial 3 - Sessions, Configurations, Data Model and `get_data`

## LSEG Data Model

The LSEG Data Platform is, well, a platform. More specifically, this platform hosts many API Families which themselves host individual APIs which allow users to access data (e.g.: historical end-of-business-day (i.e.: close) prices for a company's publicly floated equity (i.e.: stock)) or services (e.g.: calculations). Each individual service within each API can be accessed via endpoints, that are simply just addresses where our computers can send requests. You can think of this like your computer sending a letter detailing the request you asked for; e.g.: Vodafone's stock price last year. You need to know which endpoint to use when sending requests. Documentation about endpoint names, and the structure in which requests can be made can be found on the [API Playground](https://apidocs.refinitiv.com/Apps/ApiDocs). This playground is, however, behind a paywall accesible only to LSEG clients via their user credentials (username and passwords). But you may be interested in the Data Model before becoming a client, so to serve such stakeholders, we have created the [LSEG Developer Portal](https://developers.lseg.com/en) on which detailed Documentation (and more) can be found (mostly) publicly. You can also find informaion about other APIs (i.e.: APIs not hosted within the LSEG Data Platform, e.g.: Datastream) on this Developer Portal, but these are outside the scope of this tutorial.

<img src="DataModel.PNG">

## LSEG Data Library

Anyone with a license can send requests to these endpoints and receive a response. One may choose to program their computer to do so using C++ or JAVA or any other coding language of choice; however, we decided to help developers and created functions in the most popular programing languages, Python, TypeScript and .Net. These functions were simple when 1st developed (e.g.: send all requests to the `historical-pricing` endpoint because it is the most popular one), but got more complex with time. In the case of Python, we decided to wrap as many functions as possible into a library, the LSEG Data Library (LDL).

Within this library, you can use the Delivery Layer functions to send requests to specific endpoints, but it is the most complex use-case of the LDL, since it requires us to know exactly which endpoint to use, and how to request for data/services from that assosiated API. We therefore created another set of functions, called the Content Layer, which renamed endpoints to more intuitive names, and allows us to structure our requests in a simpler, uniform, way. We noticed, however, that that some functions were more popular than others, much more, and therefore decided to siplify them even more! We packaged these into the last layer, the Access Layer.

Since the Access Layer is the simplest, we will start our tutorial there.

## Install & Import the LSEG Data Library

To install libraries in python, you can find the command in PyPl, in this instance, it is:

In [1]:
# pip install lseg.data

In [3]:
import lseg.data as ld

## Quick Introduction to the Workspace Desktop App, Workspace Web app, and LDL Sessions

1st, a little refresh on the clasical ‘product’ LSEG sells: the [Workspace Desktop App](https://www.refinitiv.com/en/products/refinitiv-workspace/download-workspace?_ga=2.91796954.1111853358.1688972213-1243864833.1674474112). Desktop apps differ from other applications in that they have to be downloaded and installed on your machine to work; one cannot, for example, access it on a web-page. They exist in contrast to their Web Apps; indeed, as per popular demand, we’ve made a web version of the LSEG Workspace application too: [Workspace Web](https://eikon.thomsonreuters.com/index.html), for which training can be found [here](https://my.refinitiv.com/content/mytr/en/policies/training-portal/refinitivworkspacenew/refinitivworkspacewebaccess.html?_ga=2.59282029.1111853358.1688972213-1243864833.1674474112).

The Workspace Desktop App is a desktop application that works on Windows and Mac. We are still in the process of onboarding all our datasets on that app, meaning that some (but few) datasets viewable on the Workspace Desktop App are not available via the LSEG Data Platform, and *vice versa*. On the other hand, we are also onboarding new datasets all the time, as per the nature of our company, and we tend to onboard them on both the Workspace Desktop App and LSEG Data Platform, to homogenise our data models.

N.B.: While some data providers are incorporated into our Apps and [APIs](https://www.mulesoft.com/resources/api/what-is-an-api), they might require you to pay them directly and get a license with them directly (e.g.: if you would like MSCI dataset access on LSEG Apps, you will need an MSCI license with MSCI separate from any LSEG license you may have).

The LSEG Data Platform can only be used with one of two sessions called ‘desktop’ and ‘platform’. When using the desktop session, one needs to their Workspace Desktop App running on the machine on which the API (LDL) is being used; this is not required when using the platform session.

a. When using the desktop session, the only credential needed to access Refinitiv datasets is your app key, information for which can be found [here](https://developers.refinitiv.com/en/api-catalog/eikon/eikon-data-api/quick-start); this is because the desktop app handles all other credentials to authenticate you to the LSEG system.

b. When using the platform session, one needs their App Key and user credentials (login & password).

## Desktop Session

### Authentification to LSEG Service

Desktop session use-cases are the simples ones, so let's start there. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

In [4]:
ld.open_session()

### Access Layer

As aformentioned, there are 3 layers, the Delivery Layer, the Content Layer and the Access Layer. The Access Layer is the simplest, so let's start there.

### `get_data`

The most 'bare bones' function within the Access Layer is the `get_data` function, in that it (i) simply just colects data from LSEG databases 'as-is' (i.e.: with very few ordering rules or filters) and it (ii) is the closest to data retreival functions LSEG created for old LDL versions (e.g.: the Refinitiv Data Library for Python, or the Eikon Data API). It stands most in contrast to the `get_hisoty` function; more on that function later.

The LDL has 4 arguments:

(i) universe: in which you can put your universe (list) of securities for which you would like to colect data, and for which you can find information on the Workspace App (be it the desktop or web app)

In [8]:
ld.get_data(
    universe=['VOD.L', 'AAPL.O'],
    fields=['TR.Close'])

  Instrument  Price Close
0      VOD.L        76.84
1     AAPL.O       194.35

(ii) fields: in which you can put your list of fields you are interested in for your universe (for which you can find information with the [Data Item Browser](https://developers.lseg.com/en/search-results?q=data+item+browser), isetlf in the Workspace app)

In [9]:
ld.get_data(
    universe=['VOD.L', 'AAPL.O'],
    fields=[
        'Instrument', 'PROD_PERM', 'RDNDISPLAY',
        'DSPLY_NAME', 'RDN_EXCHID', 'TRDPRC_1',
        'TRDPRC_2', 'TRDPRC_3', 'TRDPRC_4', 'TRDPRC_5',
        'IRG_EXID', 'CLS_EXID', 'CAN_EXID', 'BLK_DATE',
        'ODD_DATE', 'ODD_EXID', 'BLK_EXID', 'BLKTIM_NS',
        'ODDTIM_NS', 'OPEN_T_NS'])  # `VOD.L` and `AAPL.O` are the RICs for Vodafone and Apple inc. respectively.

,Instrument,INSTRUMENT,PROD_PERM,RDNDISPLAY,DSPLY_NAME,RDN_EXCHID,TRDPRC_1,TRDPRC_2,TRDPRC_3,TRDPRC_4,...,IRG_EXID,CLS_EXID,CAN_EXID,BLK_DATE,ODD_DATE,ODD_EXID,BLK_EXID,BLKTIM_NS,ODDTIM_NS,OPEN_T_NS
0,VOD.L,<NA>,9241,115,VODAFONE GRP/d,LSE,77.447,77.46,77.46,77.445,...,<NA>,<NA>,<NA>,NaT,NaT,<NA>,<NA>,<NA>,<NA>,<NA>
1,AAPL.O,<NA>,5050,66,APPLE INC/d,,<NA>,<NA>,<NA>,<NA>,...,PSE,NAS,<NA>,NaT,2024-06-05,PSE,<NA>,<NA>,08:29:28,<NA>

(iii) parameters: in which you can specify parameters such as the start and end dates for your requests (among very many other things):

In [10]:
ld.get_data(
    universe=['VOD.L', 'AAPL.O'],
    fields=['TR.Close.date', 'TR.Close'],
    parameters={
        'SDate': '2020-01-01',
        'EDate': '2020-01-09'})

   Instrument       Date  Price Close
0       VOD.L 2020-01-02        147.8
1       VOD.L 2020-01-03       147.94
2       VOD.L 2020-01-06       147.08
3       VOD.L 2020-01-07       146.66
4       VOD.L 2020-01-08        147.5
5       VOD.L 2020-01-09       151.96
6      AAPL.O 2020-01-02      75.0875
7      AAPL.O 2020-01-03      74.3575
8      AAPL.O 2020-01-06        74.95
9      AAPL.O 2020-01-07      74.5975
10     AAPL.O 2020-01-08      75.7975
11     AAPL.O 2020-01-09      77.4075

I wanted to find other such examples, so I had a look on CODECR:

<img src="CODECR.PNG">

In [11]:
ld.get_data(
    universe=['VOD.L', 'AAPL.O'],
    fields=['TR.EventStartDate', 'TR.EventType', 'TR.EventTitle'],
    parameters={
        'SDate' : '2024-01-01',
        'EDate' : '-1AM',
        'EventType' : 'ECALL:RES:GCALL:CAM:BAM:CONF:IPOF'})

,Instrument,Event Start Date,Company Event Type,Event Title
0,VOD.L,2024-02-05,EarningsReleases,Q3 2023 Vodafone Group PLC Earnings Release
1,AAPL.O,2024-02-01,EarningsReleases,Q1 2024 Apple Inc Earnings Release
2,AAPL.O,2024-02-01,EarningsCallsAndPresentations,Q1 2024 Apple Inc Earnings Call
3,AAPL.O,2024-05-02,EarningsReleases,Q2 2024 Apple Inc Earnings Release
4,AAPL.O,2024-05-02,EarningsCallsAndPresentations,Q2 2024 Apple Inc Earnings Call

In [12]:
ld.get_data(
    universe = ['LSUc1'],
    fields = ['CF_ASK',
              'TR.ACCUMULATEDVOLUME',
              'TR.SELLVOLUME',
              'TR.COMBINEDACCUMULATEDVOLUME',
              'TR.TSVWAP'],
    parameters={'Frq': 'D',
                'SDate': '0',
                'EDate': '-100',
                'Curn': 'Native',
                'DOW': 'Monday',
                'CALCMETHOD': 'HIGH'})

,Instrument,Date,Accumulated Volume,Sell Volume,Combined Accumulated Volume,VWAP
0,LSUc1,2024-06-03,5829,,,550.01
1,LSUc1,2024-05-20,8750,,,546.53
2,LSUc1,2024-05-13,11171,,,558.39
3,LSUc1,2024-04-29,7738,,,569.43
4,LSUc1,2024-04-22,6777,,,572.15
5,LSUc1,2024-04-15,375,,,628.79
6,LSUc1,2024-04-08,9915,,,642.01
7,LSUc1,2024-03-25,5025,,,641.72
8,LSUc1,2024-03-18,5372,,,626.86
9,LSUc1,2024-03-11,5529,,,612.61
10,LSUc1,2024-03-04,10031,,,599.21
11,LSUc1,2024-02-26,7554,,,620.65

(iv) HeaderType:

In [13]:
ld.get_data(
    universe=['VOD.L', 'AAPL.O'],
    fields=['TR.Close.date', 'TR.Close'],
    parameters={
        'SDate': '2020-01-01',
        'EDate': '2020-01-09'},
    header_type=ld.HeaderType.TITLE)

   Instrument TR.CLOSE.DATE  TR.CLOSE
0       VOD.L    2020-01-02     147.8
1       VOD.L    2020-01-03    147.94
2       VOD.L    2020-01-06    147.08
3       VOD.L    2020-01-07    146.66
4       VOD.L    2020-01-08     147.5
5       VOD.L    2020-01-09    151.96
6      AAPL.O    2020-01-02   75.0875
7      AAPL.O    2020-01-03   74.3575
8      AAPL.O    2020-01-06     74.95
9      AAPL.O    2020-01-07   74.5975
10     AAPL.O    2020-01-08   75.7975
11     AAPL.O    2020-01-09   77.4075

### Where to go to figure out the available fields that I can access using the Data Libraries (such as the LD Python Library)?

Now that you have access to the LSEG API functions in Python, how can you figure out what field names you can use? You can using Workspace to figure out available fields, as shown [here](https://developers.refinitiv.com/en/article-catalog/article/summary-of-common-lseg-refinitiv-apis), but I prefer using the [DIB](https://developers.refinitiv.com/en/video-catalog/data-item-browser):

In DIB, I search ‘Vodafone’ for the instrument to request and ‘average daily value’ for the field. You get automatically a list of fields matching your request. In our case, the ADV — 5 days is equal to 16.117290

<img src="https://developers.refinitiv.com/content/dam/devportal/articles/Summary-of-Common-LSEG-Refinitiv-APIs/e.png">

## Platform Session

Platform sessions allow us to use the LD Lib. without the Workspace Desktop App open. It was created for servers, and it is still aimed for data hungry users who require little human interation with the code at hand (e.g.: overnight data retraival). With that said, usecases have grown in breadth and complexity thoughout the years, and people may want such 'ping' services (i.e.: the ability to 'ping', to directly contact, the services that deliver data/calculations, without going through the Desktop App Proxy).

Platform session use-cases are a little more complicated to the Desktop session ones. We can authenticate ourselves with the Workspace Desktop App open with simply just the Python line:

Open a session by name

In [14]:
ld.close_session() # We need to close out previous session to open a new one.

You will need a configuration file to authenticate yourself to the LSEG services. I named mine "refinitiv-data.config.json" and put them in the location "C:/Example.DataLibrary.Python-main/Configuration/"; it resembles somehting like this:

<img src="https://developers.lseg.com/content/dam/devportal/articles/Summary-of-Common-LSEG-Refinitiv-APIs/c.png">

In [23]:
ld.open_session(
    config_name="C:/Example.DataLibrary.Python-main/Configuration/refinitiv-data.config.json",
    name="platform.jlrdp")

In [24]:
ld.get_data(
    universe=['VOD.L', 'AAPL.O'],
    fields=['TR.Close.date', 'TR.Close'],
    parameters={
        'SDate': '2020-01-01',
        'EDate': '2020-01-09'})

   Instrument       Date  Price Close
0       VOD.L 2020-01-02        147.8
1       VOD.L 2020-01-03       147.94
2       VOD.L 2020-01-06       147.08
3       VOD.L 2020-01-07       146.66
4       VOD.L 2020-01-08        147.5
5       VOD.L 2020-01-09       151.96
6      AAPL.O 2020-01-02      75.0875
7      AAPL.O 2020-01-03      74.3575
8      AAPL.O 2020-01-06        74.95
9      AAPL.O 2020-01-07      74.5975
10     AAPL.O 2020-01-08      75.7975
11     AAPL.O 2020-01-09      77.4075

In [25]:
ld.close_session()