<img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="28%" align="left" style="vertical-align: top; padding-top: 23px;">
<img src="http://hilpisch.com/tpq_logo_long.png" width="36%" align="right" style="vertical-align: top;">

# LSEG Data Python Library

**Python Wrapper Package &mdash; Data Retrieval**

Dr. Yves J. Hilpisch | The Python Quants GmbH

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>

<img src="http://hilpisch.com/images/tr_eikon_02.png" width=350px align=left>

## The Agenda

This tutorial covers the **basic functions** of the `LSEG Data` Python wrapper package:

* `lseg.data` package
* `ld.content.symbol_conversion`
* `ld.get_data()`
* `ld.get_history()`
* `ld.news.get_headlines`

## Installation

The **Python wrapper package** for the LSEG Data Python Library named `lseg.data`.

It is **installed** via `pip`:
    
    pip install lseg.data
    
It can also be **upgraded** via `pip`:

    pip install lseg.data --upgrade

## Imports and Versions

The following imports several **packages** as used in the following.

In [1]:
import lseg.data as ld  # the LSEG Python wrapper package
import cufflinks as cf  # Cufflinks
import configparser as cp
cf.set_config_file(offline=True)  # set the plotting mode to offline

The following **Python and package versions** are used.

In [2]:
import sys
print(sys.version)

3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]

In [3]:
ld.__version__

'1.5.1.dev97+g1dedf55e'

In [4]:
cf.__version__

'0.17.3'

## Connecting to LSEG's services

The LSEG Data Platform hosts many API Families which themselves host individual APIs which allow users to access data (e.g.: historical end-of-business-day (i.e.: close) prices for a company's publicly floated equity (i.e.: stock)) or services (e.g.: calculations). The [LSEG Data Python Library](https://developers.lseg.com/en) allows us to connect to this platform, and we can authenticate ourselves with the following code:

In [5]:
ld.open_session()

c:\Users\U6082174\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning:

urllib3 (2.2.0) or chardet (None)/charset_normalizer (2.1.1) doesn't match a supported version!

## Functions

The Python function `help()` can be used to look up the **help texts** for all elements of the Python wrapper package.

In [7]:
help(ld)

Help on package lseg.data in lseg:

NAME
    lseg.data - lseg-data is a Python library to access Data Platform with Python.

PACKAGE CONTENTS
    _access_layer (package)
    _adc_headers (package)
    _base_enum
    _config_defaults
    _configure
    _content_type
    _core (package)
    _errors
    _external_libraries (package)
    _layer_type
    _listener
    _log
    _open_state
    _tools (package)
    _types
    _version
    content (package)
    delivery (package)
    discovery (package)
    early_access (package)
    errors
    session (package)
    usage_collection (package)
    warnings

SUBMODULES
    dates_and_calendars
    news

CLASSES
    contextlib.AbstractContextManager(abc.ABC)
        lseg.data._access_layer.get_stream.PricingStream
    enum.Enum(builtins.object)
        lseg.data._open_state.OpenState
        lseg.data.content._header_type.HeaderType

    class HeaderType(enum.Enum)
     |  HeaderType(value, names=None, *, module=None, qualname=None, type=None, start=1, boundary=None)
     |
     |  Method resolution order:
     |      HeaderType
     |      enum.Enum
     |      builtins.object
     |
     |  Data and other attributes defined here:
     |
     |  NAME = <HeaderType.NAME: 1>
     |
     |  NAME_AND_TITLE = <HeaderType.NAME_AND_TITLE: 3>
     |
     |  TITLE = <HeaderType.TITLE: 2>
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |
     |  name
     |      The name of the Enum member.
     |
     |  value
     |      The value of the Enum member.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from enum.EnumType:
     |
     |  __contains__(member) from enum.EnumType
     |      Return True if member is a member of this enum
     |      raises TypeError if member is not an enum member
     |
     |      note: in 3.12 TypeError will no longer be raised, and True will also be
     |      returned if member is the value of a member in this enum
     |
     |  __getitem__(name) from enum.EnumType
     |      Return the member matching `name`.
     |
     |  __iter__() from enum.EnumType
     |      Return members in definition order.
     |
     |  __len__() from enum.EnumType
     |      Return the number of members (no aliases)
     |
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumType:
     |
     |  __members__
     |      Returns a mapping of member name->value.
     |
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.

    class OpenState(enum.Enum)
     |  OpenState(value, names=None, *, module=None, qualname=None, type=None, start=1, boundary=None)
     |
     |  Session lifecycle state.
     |      Opened : the session is open and ready to work.
     |      Pending : the session is waiting to be opened or closed.
     |      Closed : the session is closed.
     |
     |  Method resolution order:
     |      OpenState
     |      enum.Enum
     |      builtins.object
     |
     |  Data and other attributes defined here:
     |
     |  Closed = <OpenState.Closed: 'Closed'>
     |
     |  Opened = <OpenState.Opened: 'Opened'>
     |
     |  Pending = <OpenState.Pending: 'Pending'>
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |
     |  name
     |      The name of the Enum member.
     |
     |  value
     |      The value of the Enum member.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from enum.EnumType:
     |
     |  __contains__(member) from enum.EnumType
     |      Return True if member is a member of this enum
     |      raises TypeError if member is not an enum member
     |
     |      note: in 3.12 TypeError will no longer be raised, and True will also be
     |      returned if member is the value of a member in this enum
     |
     |  __getitem__(name) from enum.EnumType
     |      Return the member matching `name`.
     |
     |  __iter__() from enum.EnumType
     |      Return members in definition order.
     |
     |  __len__() from enum.EnumType
     |      Return the number of members (no aliases)
     |
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumType:
     |
     |  __members__
     |      Returns a mapping of member name->value.
     |
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.

    class PricingStream(contextlib.AbstractContextManager)
     |  PricingStream(stream: 'MixedStreams')
     |
     |  Method resolution order:
     |      PricingStream
     |      contextlib.AbstractContextManager
     |      abc.ABC
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __enter__(self)
     |      Return `self` upon entering the runtime context.
     |
     |  __exit__(self, exc_type, exc_value, exc_traceback)
     |      Raise any exception triggered within the runtime context.
     |
     |  __getitem__(self, item) -> 'PricingStream'
     |
     |  __init__(self, stream: 'MixedStreams')
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __iter__(self)
     |
     |  add_instruments(self, *args) -> None
     |
     |  close(self) -> 'OpenState'
     |
     |  get_snapshot(self, universe: Union[str, List[str], NoneType] = None, fields: Optional[List[str]] = None, convert: bool = True) -> 'pd.DataFrame'
     |
     |  open(self, with_updates: bool = True) -> 'OpenState'
     |
     |  recorder
     |
     |  remove_instruments(self, *args) -> None
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  __abstractmethods__ = frozenset()
     |
     |  ----------------------------------------------------------------------
     |  Class methods inherited from contextlib.AbstractContextManager:
     |
     |  __class_getitem__ = GenericAlias(...) from abc.ABCMeta
     |      Represent a PEP 585 generic type
     |
     |      E.g. for t = list[int], t.__origin__ is list and t.__args__ is (int,).
     |
     |  __subclasshook__(C) from abc.ABCMeta
     |      Abstract classes can override this to customize issubclass().
     |
     |      This is invoked early on by abc.ABCMeta.__subclasscheck__().
     |      It should return True, False or NotImplemented.  If it returns
     |      NotImplemented, the normal algorithm is used.  Otherwise, it
     |      overrides the normal algorithm (and the outcome is cached).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from contextlib.AbstractContextManager:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

FUNCTIONS
    close_session() -> None
        Closes the previously opened session.

        Returns
        -------
        None

    get_config() -> lseg.data._configure._RDPConfig
        Returns
        -------
        config object

    get_data(universe: Union[str, Iterable[str]], fields: Union[str, Iterable[str], NoneType] = None, parameters: Union[str, dict, NoneType] = None, header_type: lseg.data.content._header_type.HeaderType = <HeaderType.TITLE: 2>) -> pandas.core.frame.DataFrame
        Retrieves pricing snapshots, as well as Fundamental and Reference data.

        Parameters
        ----------
        universe: str | list
            Instruments to request
        fields: str | list, optional
            Fields to request
        parameters: str | dict, optional
            Single key=value global parameter or dictionary of global parameters to request
        header_type: HeaderType, default HeaderType.TITLE
            If HeaderKey.TITLE - returns field title as column headers for data
            If HeaderKey.NAME - returns field name as column headers for data
            If HeaderKey.NAME_AND_TITLE - returns field name and title as column headers for data

        Returns
        -------
        pandas.DataFrame

        Examples
        --------
        >>> get_data(universe=['IBM.N', 'VOD.L'], fields=['BID', 'ASK'])
        >>> get_data(
        ...     universe=['GOOG.O', 'AAPL.O'],
        ...     fields=['TR.EV','TR.EVToSales'],
        ...     parameters = {'SDate': '0CY', 'Curn': 'CAD'}
        ... )

    get_history(universe: Union[str, Iterable[str]], fields: Union[str, Iterable[str], NoneType] = None, interval: Optional[str] = None, start: 'OptDateTime' = None, end: 'OptDateTime' = None, adjustments: Optional[str] = None, count: Optional[int] = None, parameters: Union[str, dict, NoneType] = None, header_type: lseg.data.content._header_type.HeaderType = <HeaderType.TITLE: 2>) -> pandas.core.frame.DataFrame
        Retrieves the pricing history, as well as Fundamental and Reference data history.

        Parameters
        ----------
        universe: str | list
            Instruments to request
        fields: str | list, optional
            Fields to request
        interval: str, optional
            Date interval. Supported intervals are:
            tick, tas, taq, minute, 1min, 5min, 10min, 30min, 60min, hourly, 1h, daily,
            1d, 1D, 7D, 7d, weekly, 1W, monthly, 1M, quarterly, 3M, 6M, yearly, 1Y
        start: str or date or datetime or timedelta, optional
            The start date and timestamp of the requested history
        end: str or date or datetime or timedelta, optional
            The end date and timestamp of the requested history
        adjustments : str, optional
            Tells the system whether to apply or not apply CORAX (Corporate Actions)
            events or exchange/manual corrections or price and volume adjustment
            according to trade/quote qualifier summarization actions to historical time
            series data. Possible values are:
            exchangeCorrection, manualCorrection, CCH, CRE, RTS, RPO, unadjusted,
            qualifiers
        count : int, optional
            The maximum number of data points returned. Values range: 1 - 10000.
            Applies only to pricing fields.
        parameters: str | dict, optional
            Single global parameter key=value or dictionary
            of global parameters to request.
            Applies only to TR fields.
        header_type: HeaderKey, default HeaderKey.TITLE
            If HeaderKey.TITLE - returns field title as column headers for data
            If HeaderKey.NAME - returns field name as column headers for data
            If HeaderKey.NAME_AND_TITLE - returns field name and title as column headers for data

        Returns
        -------
        pandas.DataFrame

        Examples
        --------
        >>> get_history(universe="GOOG.O")
        >>> get_history(universe="GOOG.O", fields="tr.Revenue", interval="1Y")
        >>> get_history(
        ...     universe="GOOG.O",
        ...     fields=["BID", "ASK", "tr.Revenue"],
        ...     interval="1Y",
        ...     start="2015-01-01",
        ...     end="2020-10-01",
        ... )

    load_config(path: Optional[str]) -> lseg.data._configure._RDPConfig
        Load user's config file and set this file as default.

        Parameters
        ----------
            path: str
                Path to user's config file.

        Raises
        ----------
        Exception
            If can't find file by path that user provided

        Returns
        ----------
        config object

    open_pricing_stream(universe: Union[str, Iterable[str]], fields: Union[str, List[str]] = None, service: Optional[str] = None, on_data: Optional[Callable] = None) -> 'PricingStream'
        Creates and opens a pricing stream.

        Parameters
        ----------
        universe : str | List[str]
            Instruments to request.
        fields : str | list, optional
            Fields to request.
        service : str, optional
            Name of the streaming service publishing the instruments.
        on_data : function, optional
            Callback function.

        Returns
        ----------
        PricingStream

        Examples
        -------
        >>> import lseg.data as ld
        >>> def callback(updated_data, ric, stream):
        ...    print(updated_data)
        >>> pricing_stream = ld.open_pricing_stream(universe=['EUR='], fields=['BID', 'ASK', 'OPEN_PRC'], on_data=callback)  # noqa

    open_session(name: Optional[str] = None, app_key: Optional[str] = None, config_name: Optional[str] = None) -> 'Session'
        Opens and returns a session.

        Parameters
        ----------
        name: str, optional
            Session name from the config file.
        app_key: str, optional
            The application key.
        config_name: str, optional
            The config name. If provided, overrides default config.

        Returns
        -------
        Session

VERSION
    1.5.1.dev97+g1dedf55e

FILE
    c:\users\u6082174\appdata\local\programs\python\python311\lib\site-packages\lseg\data\__init__.py

In addition, from within Jupyter Notebook, for example, you can use **tab completion** to look up available functionality:

In [8]:
# ld.  # uncomment & place cursor behind dot, then press the tab key

The `ld` package (i.e.: the `lseg.data` package) provides the following **basic functions** to interact with the Eikon Data API and to retrieve data of different types:

* `ld.content.symbol_conversion`: converting symbology types
* `ld.get_data()`: retrieve historical data
* `ld.get_history()`: retrieve historical time series data
* `ld.news.get_headlines()`: retrieve news headlines

## `ld.content.symbol_conversion`

The function `ld.content.symbol_conversion` allows you to **convert symbols** from one symbology type to another.

In [9]:
help(ld.content.symbol_conversion)

Help on package lseg.data.content.symbol_conversion in lseg.data.content:

NAME
    lseg.data.content.symbol_conversion

DESCRIPTION
    The SymbolConversion content object allows you to convert various types of symbols like RICs, ISINs, CUSIPs,
    and so on, using the Search/Lookup API of the Data Platform.

PACKAGE CONTENTS
    _asset_class
    _asset_state
    _country_code
    _definition
    _symbol_type

CLASSES
    enum.StrEnum(builtins.str, enum.ReprEnum)
        lseg.data.content.symbol_conversion._asset_class.AssetClass
        lseg.data.content.symbol_conversion._asset_state.AssetState
        lseg.data.content.symbol_conversion._country_code.CountryCode
        lseg.data.content.symbol_conversion._symbol_type.SymbolTypes
    lseg.data.content._content_provider_layer.ContentProviderLayer(lseg.data.content._content_provider_layer.ContentUsageLoggerMixin, lseg.data.delivery._data._data_provider_layer.DataProviderLayer)
        lseg.data.content.symbol_conversion._definition.Definition

    class AssetClass(enum.StrEnum)
     |  AssetClass(value, names=None, *, module=None, qualname=None, type=None, start=1, boundary=None)
     |
     |  Asset class values to build 'filter' parameter in request for SymbolConversion content object.
     |
     |  Method resolution order:
     |      AssetClass
     |      enum.StrEnum
     |      builtins.str
     |      enum.ReprEnum
     |      enum.Enum
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __format__(self, format_spec, /)
     |      Return a formatted version of the string as described by format_spec.
     |
     |  __new__(cls, value)
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  BONDS = <AssetClass.BONDS: 'Bonds'>
     |
     |  BOND_AND_STIR_FUTURES_AND_OPTIONS = <AssetClass.BOND_AND_STIR_FUTURES_...
     |
     |  CERTIFICATES = <AssetClass.CERTIFICATES: 'Certificates'>
     |
     |  COMMODITIES = <AssetClass.COMMODITIES: 'Commodities'>
     |
     |  EQUITIES = <AssetClass.EQUITIES: 'Equities'>
     |
     |  EQUITY_INDEX_FUTURES = <AssetClass.EQUITY_INDEX_FUTURES: 'EquityIndexF...
     |
     |  EQUITY_OR_INDEX_OPTIONS = <AssetClass.EQUITY_OR_INDEX_OPTIONS: 'Equity...
     |
     |  FUNDS = <AssetClass.FUNDS: 'Funds'>
     |
     |  FX_AND_MONEY = <AssetClass.FX_AND_MONEY: 'FXAndMoney'>
     |
     |  INDICES = <AssetClass.INDICES: 'Indices'>
     |
     |  MINI_FUTURE = <AssetClass.MINI_FUTURE: 'MiniFuture'>
     |
     |  RESERVE_CONVERTIBLE = <AssetClass.RESERVE_CONVERTIBLE: 'ReverseConvert...
     |
     |  WARRANTS = <AssetClass.WARRANTS: 'Warrants'>
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from enum.StrEnum:
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.str:
     |
     |  __add__(self, value, /)
     |      Return self+value.
     |
     |  __contains__(self, key, /)
     |      Return key in self.
     |
     |  __eq__(self, value, /)
     |      Return self==value.
     |
     |  __ge__(self, value, /)
     |      Return self>=value.
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __getitem__(self, key, /)
     |      Return self[key].
     |
     |  __getnewargs__(...)
     |
     |  __gt__(self, value, /)
     |      Return self>value.
     |
     |  __hash__(self, /)
     |      Return hash(self).
     |
     |  __iter__(self, /)
     |      Implement iter(self).
     |
     |  __le__(self, value, /)
     |      Return self<=value.
     |
     |  __len__(self, /)
     |      Return len(self).
     |
     |  __lt__(self, value, /)
     |      Return self<value.
     |
     |  __mod__(self, value, /)
     |      Return self%value.
     |
     |  __mul__(self, value, /)
     |      Return self*value.
     |
     |  __ne__(self, value, /)
     |      Return self!=value.
     |
     |  __rmod__(self, value, /)
     |      Return value%self.
     |
     |  __rmul__(self, value, /)
     |      Return value*self.
     |
     |  __sizeof__(self, /)
     |      Return the size of the string in memory, in bytes.
     |
     |  capitalize(self, /)
     |      Return a capitalized version of the string.
     |
     |      More specifically, make the first character have upper case and the rest lower
     |      case.
     |
     |  casefold(self, /)
     |      Return a version of the string suitable for caseless comparisons.
     |
     |  center(self, width, fillchar=' ', /)
     |      Return a centered string of length width.
     |
     |      Padding is done using the specified fill character (default is a space).
     |
     |  count(...)
     |      S.count(sub[, start[, end]]) -> int
     |
     |      Return the number of non-overlapping occurrences of substring sub in
     |      string S[start:end].  Optional arguments start and end are
     |      interpreted as in slice notation.
     |
     |  encode(self, /, encoding='utf-8', errors='strict')
     |      Encode the string using the codec registered for encoding.
     |
     |      encoding
     |        The encoding in which to encode the string.
     |      errors
     |        The error handling scheme to use for encoding errors.
     |        The default is 'strict' meaning that encoding errors raise a
     |        UnicodeEncodeError.  Other possible values are 'ignore', 'replace' and
     |        'xmlcharrefreplace' as well as any other name registered with
     |        codecs.register_error that can handle UnicodeEncodeErrors.
     |
     |  endswith(...)
     |      S.endswith(suffix[, start[, end]]) -> bool
     |
     |      Return True if S ends with the specified suffix, False otherwise.
     |      With optional start, test S beginning at that position.
     |      With optional end, stop comparing S at that position.
     |      suffix can also be a tuple of strings to try.
     |
     |  expandtabs(self, /, tabsize=8)
     |      Return a copy where all tab characters are expanded using spaces.
     |
     |      If tabsize is not given, a tab size of 8 characters is assumed.
     |
     |  find(...)
     |      S.find(sub[, start[, end]]) -> int
     |
     |      Return the lowest index in S where substring sub is found,
     |      such that sub is contained within S[start:end].  Optional
     |      arguments start and end are interpreted as in slice notation.
     |
     |      Return -1 on failure.
     |
     |  format(...)
     |      S.format(*args, **kwargs) -> str
     |
     |      Return a formatted version of S, using substitutions from args and kwargs.
     |      The substitutions are identified by braces ('{' and '}').
     |
     |  format_map(...)
     |      S.format_map(mapping) -> str
     |
     |      Return a formatted version of S, using substitutions from mapping.
     |      The substitutions are identified by braces ('{' and '}').
     |
     |  index(...)
     |      S.index(sub[, start[, end]]) -> int
     |
     |      Return the lowest index in S where substring sub is found,
     |      such that sub is contained within S[start:end].  Optional
     |      arguments start and end are interpreted as in slice notation.
     |
     |      Raises ValueError when the substring is not found.
     |
     |  isalnum(self, /)
     |      Return True if the string is an alpha-numeric string, False otherwise.
     |
     |      A string is alpha-numeric if all characters in the string are alpha-numeric and
     |      there is at least one character in the string.
     |
     |  isalpha(self, /)
     |      Return True if the string is an alphabetic string, False otherwise.
     |
     |      A string is alphabetic if all characters in the string are alphabetic and there
     |      is at least one character in the string.
     |
     |  isascii(self, /)
     |      Return True if all characters in the string are ASCII, False otherwise.
     |
     |      ASCII characters have code points in the range U+0000-U+007F.
     |      Empty string is ASCII too.
     |
     |  isdecimal(self, /)
     |      Return True if the string is a decimal string, False otherwise.
     |
     |      A string is a decimal string if all characters in the string are decimal and
     |      there is at least one character in the string.
     |
     |  isdigit(self, /)
     |      Return True if the string is a digit string, False otherwise.
     |
     |      A string is a digit string if all characters in the string are digits and there
     |      is at least one character in the string.
     |
     |  isidentifier(self, /)
     |      Return True if the string is a valid Python identifier, False otherwise.
     |
     |      Call keyword.iskeyword(s) to test whether string s is a reserved identifier,
     |      such as "def" or "class".
     |
     |  islower(self, /)
     |      Return True if the string is a lowercase string, False otherwise.
     |
     |      A string is lowercase if all cased characters in the string are lowercase and
     |      there is at least one cased character in the string.
     |
     |  isnumeric(self, /)
     |      Return True if the string is a numeric string, False otherwise.
     |
     |      A string is numeric if all characters in the string are numeric and there is at
     |      least one character in the string.
     |
     |  isprintable(self, /)
     |      Return True if the string is printable, False otherwise.
     |
     |      A string is printable if all of its characters are considered printable in
     |      repr() or if it is empty.
     |
     |  isspace(self, /)
     |      Return True if the string is a whitespace string, False otherwise.
     |
     |      A string is whitespace if all characters in the string are whitespace and there
     |      is at least one character in the string.
     |
     |  istitle(self, /)
     |      Return True if the string is a title-cased string, False otherwise.
     |
     |      In a title-cased string, upper- and title-case characters may only
     |      follow uncased characters and lowercase characters only cased ones.
     |
     |  isupper(self, /)
     |      Return True if the string is an uppercase string, False otherwise.
     |
     |      A string is uppercase if all cased characters in the string are uppercase and
     |      there is at least one cased character in the string.
     |
     |  join(self, iterable, /)
     |      Concatenate any number of strings.
     |
     |      The string whose method is called is inserted in between each given string.
     |      The result is returned as a new string.
     |
     |      Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'
     |
     |  ljust(self, width, fillchar=' ', /)
     |      Return a left-justified string of length width.
     |
     |      Padding is done using the specified fill character (default is a space).
     |
     |  lower(self, /)
     |      Return a copy of the string converted to lowercase.
     |
     |  lstrip(self, chars=None, /)
     |      Return a copy of the string with leading whitespace removed.
     |
     |      If chars is given and not None, remove characters in chars instead.
     |
     |  partition(self, sep, /)
     |      Partition the string into three parts using the given separator.
     |
     |      This will search for the separator in the string.  If the separator is found,
     |      returns a 3-tuple containing the part before the separator, the separator
     |      itself, and the part after it.
     |
     |      If the separator is not found, returns a 3-tuple containing the original string
     |      and two empty strings.
     |
     |  removeprefix(self, prefix, /)
     |      Return a str with the given prefix string removed if present.
     |
     |      If the string starts with the prefix string, return string[len(prefix):].
     |      Otherwise, return a copy of the original string.
     |
     |  removesuffix(self, suffix, /)
     |      Return a str with the given suffix string removed if present.
     |
     |      If the string ends with the suffix string and that suffix is not empty,
     |      return string[:-len(suffix)]. Otherwise, return a copy of the original
     |      string.
     |
     |  replace(self, old, new, count=-1, /)
     |      Return a copy with all occurrences of substring old replaced by new.
     |
     |        count
     |          Maximum number of occurrences to replace.
     |          -1 (the default value) means replace all occurrences.
     |
     |      If the optional argument count is given, only the first count occurrences are
     |      replaced.
     |
     |  rfind(...)
     |      S.rfind(sub[, start[, end]]) -> int
     |
     |      Return the highest index in S where substring sub is found,
     |      such that sub is contained within S[start:end].  Optional
     |      arguments start and end are interpreted as in slice notation.
     |
     |      Return -1 on failure.
     |
     |  rindex(...)
     |      S.rindex(sub[, start[, end]]) -> int
     |
     |      Return the highest index in S where substring sub is found,
     |      such that sub is contained within S[start:end].  Optional
     |      arguments start and end are interpreted as in slice notation.
     |
     |      Raises ValueError when the substring is not found.
     |
     |  rjust(self, width, fillchar=' ', /)
     |      Return a right-justified string of length width.
     |
     |      Padding is done using the specified fill character (default is a space).
     |
     |  rpartition(self, sep, /)
     |      Partition the string into three parts using the given separator.
     |
     |      This will search for the separator in the string, starting at the end. If
     |      the separator is found, returns a 3-tuple containing the part before the
     |      separator, the separator itself, and the part after it.
     |
     |      If the separator is not found, returns a 3-tuple containing two empty strings
     |      and the original string.
     |
     |  rsplit(self, /, sep=None, maxsplit=-1)
     |      Return a list of the substrings in the string, using sep as the separator string.
     |
     |        sep
     |          The separator used to split the string.
     |
     |          When set to None (the default value), will split on any whitespace
     |          character (including \\n \\r \\t \\f and spaces) and will discard
     |          empty strings from the result.
     |        maxsplit
     |          Maximum number of splits (starting from the left).
     |          -1 (the default value) means no limit.
     |
     |      Splitting starts at the end of the string and works to the front.
     |
     |  rstrip(self, chars=None, /)
     |      Return a copy of the string with trailing whitespace removed.
     |
     |      If chars is given and not None, remove characters in chars instead.
     |
     |  split(self, /, sep=None, maxsplit=-1)
     |      Return a list of the substrings in the string, using sep as the separator string.
     |
     |        sep
     |          The separator used to split the string.
     |
     |          When set to None (the default value), will split on any whitespace
     |          character (including \\n \\r \\t \\f and spaces) and will discard
     |          empty strings from the result.
     |        maxsplit
     |          Maximum number of splits (starting from the left).
     |          -1 (the default value) means no limit.
     |
     |      Note, str.split() is mainly useful for data that has been intentionally
     |      delimited.  With natural text that includes punctuation, consider using
     |      the regular expression module.
     |
     |  splitlines(self, /, keepends=False)
     |      Return a list of the lines in the string, breaking at line boundaries.
     |
     |      Line breaks are not included in the resulting list unless keepends is given and
     |      true.
     |
     |  startswith(...)
     |      S.startswith(prefix[, start[, end]]) -> bool
     |
     |      Return True if S starts with the specified prefix, False otherwise.
     |      With optional start, test S beginning at that position.
     |      With optional end, stop comparing S at that position.
     |      prefix can also be a tuple of strings to try.
     |
     |  strip(self, chars=None, /)
     |      Return a copy of the string with leading and trailing whitespace removed.
     |
     |      If chars is given and not None, remove characters in chars instead.
     |
     |  swapcase(self, /)
     |      Convert uppercase characters to lowercase and lowercase characters to uppercase.
     |
     |  title(self, /)
     |      Return a version of the string where each word is titlecased.
     |
     |      More specifically, words start with uppercased characters and all remaining
     |      cased characters have lower case.
     |
     |  translate(self, table, /)
     |      Replace each character in the string using the given translation table.
     |
     |        table
     |          Translation table, which must be a mapping of Unicode ordinals to
     |          Unicode ordinals, strings, or None.
     |
     |      The table must implement lookup/indexing via __getitem__, for instance a
     |      dictionary or list.  If this operation raises LookupError, the character is
     |      left untouched.  Characters mapped to None are deleted.
     |
     |  upper(self, /)
     |      Return a copy of the string converted to uppercase.
     |
     |  zfill(self, width, /)
     |      Pad a numeric string with zeros on the left, to fill a field of the given width.
     |
     |      The string is never truncated.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.str:
     |
     |  maketrans(...)
     |      Return a translation table usable for str.translate().
     |
     |      If there is only one argument, it must be a dictionary mapping Unicode
     |      ordinals (integers) or characters to Unicode ordinals, strings or None.
     |      Character keys will be then converted to ordinals.
     |      If there are two arguments, they must be strings of equal length, and
     |      in the resulting dictionary, each character in x will be mapped to the
     |      character at the same position in y. If there is a third argument, it
     |      must be a string, whose characters will be mapped to None in the result.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from enum.Enum:
     |
     |  __dir__(self)
     |      Returns all members and all public methods
     |
     |  __init__(self, *args, **kwds)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __reduce_ex__(self, proto)
     |      Helper for pickle.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |
     |  name
     |      The name of the Enum member.
     |
     |  value
     |      The value of the Enum member.
     |
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumType:
     |
     |  __members__
     |      Returns a mapping of member name->value.
     |
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.

Assume the following set of `RICs`.

In [10]:
rics = [
    'AAPL.O',  # Apple stock
    'AMZN.O',  # Amazon stock
    'TSLA.O',  # Tesla stock
    '.SPX',  # S&P 500 stock index
]

The **conversion** works as follows:

In [12]:
isin = ld.content.symbol_conversion.Definition(
    symbols=rics,
    from_symbol_type=ld.content.symbol_conversion.SymbolTypes.RIC,
    to_symbol_types=[ld.content.symbol_conversion.SymbolTypes.ISIN]
    ).get_data().data.df

In [13]:
isin

                                            DocumentTitle     IssueISIN
AAPL.O  Apple Inc, Ordinary Share, NASDAQ Global Selec...  US0378331005
AMZN.O  Amazon.com Inc, Ordinary Share, NASDAQ Global ...  US0231351067
TSLA.O  Tesla Inc, Ordinary Share, NASDAQ Global Selec...  US88160R1014
.SPX                   S&P 500 Index - CBOE, Equity Index          <NA>

And also the other way round, after a conversion of data structures:

In [20]:
isins = list(isin['IssueISIN'].dropna().values)

In [21]:
isins

['US0378331005', 'US0231351067', 'US88160R1014']

In [22]:
isin = ld.content.symbol_conversion.Definition(
    symbols=isins,
    from_symbol_type=ld.content.symbol_conversion.SymbolTypes.ISIN,
    to_symbol_types=[ld.content.symbol_conversion.SymbolTypes.RIC]
    ).get_data().data.df

## `ld.get_data()`

The function `ld.get_data()` is a **general purpose data retrieval** function.

In [23]:
help(ld.get_data)

Help on function get_data in module lseg.data._access_layer.get_data_func:

get_data(universe: Union[str, Iterable[str]], fields: Union[str, Iterable[str], NoneType] = None, parameters: Union[str, dict, NoneType] = None, header_type: lseg.data.content._header_type.HeaderType = <HeaderType.TITLE: 2>) -> pandas.core.frame.DataFrame
    Retrieves pricing snapshots, as well as Fundamental and Reference data.

    Parameters
    ----------
    universe: str | list
        Instruments to request
    fields: str | list, optional
        Fields to request
    parameters: str | dict, optional
        Single key=value global parameter or dictionary of global parameters to request
    header_type: HeaderType, default HeaderType.TITLE
        If HeaderKey.TITLE - returns field title as column headers for data
        If HeaderKey.NAME - returns field name as column headers for data
        If HeaderKey.NAME_AND_TITLE - returns field name and title as column headers for data

    Returns
    -------
    pandas.DataFrame

    Examples
    --------
    >>> get_data(universe=['IBM.N', 'VOD.L'], fields=['BID', 'ASK'])
    >>> get_data(
    ...     universe=['GOOG.O', 'AAPL.O'],
    ...     fields=['TR.EV','TR.EVToSales'],
    ...     parameters = {'SDate': '0CY', 'Curn': 'CAD'}
    ... )

In [28]:
data_grid = ld.get_data(
    ['IBM', 'GOOG.O', 'MSFT.O'],
    ['TR.TotalReturnYTD', 'TR.WACCBeta'])

In [29]:
data_grid

  Instrument  YTD Total Return      Beta
0        IBM          6.487662  0.718407
1     GOOG.O         25.118853  1.012238
2     MSFT.O         14.804756  0.901411

In [30]:
data_grid.set_index('Instrument')[['YTD Total Return', 'Beta']].iplot(
    kind='bar', subplots=True)

## `ld.get_history()`

The function `ld.get_history()` retrieves **time series data**.

In [32]:
help(ld.get_history)

Help on function get_history in module lseg.data._access_layer.get_history_func:

get_history(universe: Union[str, Iterable[str]], fields: Union[str, Iterable[str], NoneType] = None, interval: Optional[str] = None, start: 'OptDateTime' = None, end: 'OptDateTime' = None, adjustments: Optional[str] = None, count: Optional[int] = None, parameters: Union[str, dict, NoneType] = None, header_type: lseg.data.content._header_type.HeaderType = <HeaderType.TITLE: 2>) -> pandas.core.frame.DataFrame
    Retrieves the pricing history, as well as Fundamental and Reference data history.

    Parameters
    ----------
    universe: str | list
        Instruments to request
    fields: str | list, optional
        Fields to request
    interval: str, optional
        Date interval. Supported intervals are:
        tick, tas, taq, minute, 1min, 5min, 10min, 30min, 60min, hourly, 1h, daily,
        1d, 1D, 7D, 7d, weekly, 1W, monthly, 1M, quarterly, 3M, 6M, yearly, 1Y
    start: str or date or datetime or timedelta, optional
        The start date and timestamp of the requested history
    end: str or date or datetime or timedelta, optional
        The end date and timestamp of the requested history
    adjustments : str, optional
        Tells the system whether to apply or not apply CORAX (Corporate Actions)
        events or exchange/manual corrections or price and volume adjustment
        according to trade/quote qualifier summarization actions to historical time
        series data. Possible values are:
        exchangeCorrection, manualCorrection, CCH, CRE, RTS, RPO, unadjusted,
        qualifiers
    count : int, optional
        The maximum number of data points returned. Values range: 1 - 10000.
        Applies only to pricing fields.
    parameters: str | dict, optional
        Single global parameter key=value or dictionary
        of global parameters to request.
        Applies only to TR fields.
    header_type: HeaderKey, default HeaderKey.TITLE
        If HeaderKey.TITLE - returns field title as column headers for data
        If HeaderKey.NAME - returns field name as column headers for data
        If HeaderKey.NAME_AND_TITLE - returns field name and title as column headers for data

    Returns
    -------
    pandas.DataFrame

    Examples
    --------
    >>> get_history(universe="GOOG.O")
    >>> get_history(universe="GOOG.O", fields="tr.Revenue", interval="1Y")
    >>> get_history(
    ...     universe="GOOG.O",
    ...     fields=["BID", "ASK", "tr.Revenue"],
    ...     interval="1Y",
    ...     start="2015-01-01",
    ...     end="2020-10-01",
    ... )

For instance, the following code retries **daily closing prices**  for the four `RICs` as defined above.

In [34]:
rics

['AAPL.O', 'AMZN.O', 'TSLA.O', '.SPX']

In [38]:
data = ld.get_history(
    rics,  # the RICs
    fields='TR.PriceClose',  # close field
    start='2024-01-01',  # start date
    end='2024-05-20',  # end date
    interval='1D').dropna()

In [39]:
data.head()

Price Close  AAPL.O  AMZN.O  TSLA.O     .SPX
Date
2024-01-02   185.64  149.93  248.42  4742.83
2024-01-03   184.25  148.47  238.45  4704.81
2024-01-04   181.91  144.57  237.93  4688.68
2024-01-05   181.18  145.24  237.49  4697.24
2024-01-08   185.56   149.1  240.45  4763.54

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 97 entries, 2024-01-02 to 2024-05-20
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL.O  97 non-null     Float64
 1   AMZN.O  97 non-null     Float64
 2   TSLA.O  97 non-null     Float64
 3   .SPX    97 non-null     Float64
dtypes: Float64(4)
memory usage: 4.2 KB

Making use of `Cufflinks`, the data is visualized below.

In [41]:
data.normalize().iplot()

## `ld.news.get_headlines`

The function `ld.news.get_headlines` allows you to search for and retrieve **news headlines**, including `storyId` values needed to retrieve the full news text.

In [42]:
help(ld.news.get_headlines)

Help on function get_headlines in module lseg.data._access_layer.news._news:

get_headlines(query: str, count: int = 10, start: 'OptDateTime' = None, end: 'OptDateTime' = None, order_by: Union[str, lseg.data.content.news.headlines._sort_order.SortOrder] = <SortOrder.new_to_old: 'newToOld'>) -> pandas.core.frame.DataFrame
    Retrieves news headlines.

    Parameters
    ----------
    query: str
        The user search query for news headlines.
    count: int, optional
        Count to limit number of headlines.
    start: str or timedelta, optional
        Beginning of date range.
        String format is: '%Y-%m-%dT%H:%M:%S'. e.g. '2016-01-20T15:04:05'.
    end: str or timedelta, optional
        End of date range.
        String format is: '%Y-%m-%dT%H:%M:%S'. e.g. '2016-01-20T15:04:05'.
    order_by: str or SortOrder
        Sort order for headline items.

    Returns
    -------
    pd.DataFrame
        Headlines dataframe

    Examples
    --------
    >>> from datetime import timedelta
    >>> import lseg.data as ld
    >>> response = ld.news.get_headlines(
    ...     "Refinitiv",
    ...     start="20.03.2021",
    ...     end=timedelta(days=-4),
    ...     count=3
    ... )

A `query` string might contain `RICs` and other words to be searched for.

In [43]:
rics[2]

'TSLA.O'

In [46]:
news = ld.news.get_headlines(
    'R:%s PRODUCTION IN ENGLISH' % rics[2],
    start='2024-05-01',
    end='2024-05-14',
    count=10)

In [47]:
news

,headline,storyId,sourceCode
versionCreated,,,
2024-05-13 15:47:48.442,Tesla halts production of Model 2 to focus on ...,urn:newsml:newsroom:20240513:nNRAsnbmbo:0,NS:INVEZZ
2024-05-10 13:30:25.000,FACTBOX-Chinese EV makers set sights on Europe...,urn:newsml:reuters.com:20240510:nL1N3HD10W:6,NS:RTRS
2024-05-09 13:51:58.254,Walmart tests its 1st truck by Tesla :39 on or...,urn:newsml:newsroom:20240509:nNRAsm5bbx:0,NS:ARKDEM
2024-05-08 00:51:08.596,"Production Teams Will Be Overburdened, Says Fo...",urn:link:webnews:20240508:nNRAslgx9u:0,NS:MSNSOU
2024-05-07 19:21:58.190,Tesla Will Temporarily Stop Production At Germ...,urn:newsml:newsroom:20240507:nNRAsldupu:0,NS:BENZIN
2024-05-07 18:32:40.211,Tesla to shut down production at German plant ...,urn:link:webnews:20240507:nNRAsldjfs:0,NS:YAHNEX
2024-05-07 18:25:59.104,UPDATE 1-Tesla to shut down production at Germ...,urn:link:webnews:20240507:nNRAsle435:0,NS:YAHNEX
2024-05-07 16:01:59.847,Tesla shares are trading lower on reports the ...,urn:newsml:newsroom:20240507:nNRAslbn5o:0,NS:BENZIN
2024-05-07 15:40:11.000,TESLA SHARES MOVE LOWER AFTER REPORT CO TO SHU...,urn:newsml:reuters.com:20240507:nL4N3HA4OG:1,NS:RTRS
2024-05-07 15:30:07.000,Tesla to shut down production at German plant ...,urn:newsml:reuters.com:20240507:nL8N3HA7QO:2,NS:RTRS

### Story

The function `ld.content.news.story.Definition` retrieves the full text of a **news stroy** given the `storyId` value.

In [48]:
help(ld.content.news.story.Definition)

Help on class Definition in module lseg.data.content.news.story._definition:

class Definition(lseg.data.content.news._news_data_provider_layer.NewsDataProviderLayer)
 |  Definition(story_id: str, extended_params: 'ExtendedParams' = None)
 |
 |  This class describes parameters to retrieve data for news story.
 |
 |  Parameters
 |  ----------
 |  story_id : str
 |      The ID of news story.
 |
 |  extended_params: dict, optional
 |      Other parameters can be provided if necessary
 |
 |
 |  Examples
 |  --------
 |  >>> from lseg.data.content import news
 |  >>> definition = news.story.Definition("urn:newsml:reuters.com:20201026:nPt6BSyBh")
 |
 |  Method resolution order:
 |      Definition
 |      lseg.data.content.news._news_data_provider_layer.NewsDataProviderLayer
 |      lseg.data.content._content_provider_layer.ContentUsageLoggerMixin
 |      lseg.data.delivery._data._data_provider_layer.DataProviderLayer
 |      typing.Generic
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, story_id: str, extended_params: 'ExtendedParams' = None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {}
 |
 |  __parameters__ = ()
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from lseg.data.content.news._news_data_provider_layer.NewsDataProviderLayer:
 |
 |  get_data(self, session: Optional[ForwardRef('Session')] = None)
 |      Sends a request to the Data Platform to retrieve the predefined data.
 |
 |      Parameters
 |      ----------
 |      session : Session, optional
 |          Session object. If it's not passed the default session will be used.
 |
 |      Returns
 |      -------
 |      Response
 |          Returns as the result of successful response from Data Platform.
 |
 |  async get_data_async(self, session: Optional[ForwardRef('Session')] = None, on_response: Optional[Callable] = None, closure: Optional[str] = None)
 |      Sends an asynchronous request to the Data Platform to retrieve the predefined data.
 |
 |      Parameters
 |      ----------
 |      session : Session, optional
 |          Session object. If it's not passed the default session will be used.
 |      on_response : Callable, optional
 |          Callable function to process the retrieved data.
 |      closure : Any
 |          Closure parameters that will be returned with the response.
 |
 |      Returns
 |      -------
 |      Response
 |          Returns as the result of successful response from Data Platform.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from lseg.data.content._content_provider_layer.ContentUsageLoggerMixin:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from lseg.data.content._content_provider_layer.ContentUsageLoggerMixin:
 |
 |  __orig_bases__ = (typing.Generic[~T],)
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from typing.Generic:
 |
 |  __class_getitem__(params) from builtins.type
 |      Parameterizes a generic class.
 |
 |      At least, parameterizing a generic class is the *main* thing this method
 |      does. For example, for some generic class `Foo`, this is called when we
 |      do `Foo[int]` - there, with `cls=Foo` and `params=int`.
 |
 |      However, note that this method is also called when defining generic
 |      classes in the first place with `class Foo(Generic[T]): ...`.
 |
 |  __init_subclass__(*args, **kwargs) from builtins.type
 |      This method is called when a class is subclassed.
 |
 |      The default implementation does nothing. It may be
 |      overridden to extend subclasses.

The `storyId` values are stored in the respective column of the `news` `DataFrame` object as created above.

In [49]:
news['storyId']

versionCreated
2024-05-13 15:47:48.442       urn:newsml:newsroom:20240513:nNRAsnbmbo:0
2024-05-10 13:30:25.000    urn:newsml:reuters.com:20240510:nL1N3HD10W:6
2024-05-09 13:51:58.254       urn:newsml:newsroom:20240509:nNRAsm5bbx:0
2024-05-08 00:51:08.596          urn:link:webnews:20240508:nNRAslgx9u:0
2024-05-07 19:21:58.190       urn:newsml:newsroom:20240507:nNRAsldupu:0
2024-05-07 18:32:40.211          urn:link:webnews:20240507:nNRAsldjfs:0
2024-05-07 18:25:59.104          urn:link:webnews:20240507:nNRAsle435:0
2024-05-07 16:01:59.847       urn:newsml:newsroom:20240507:nNRAslbn5o:0
2024-05-07 15:40:11.000    urn:newsml:reuters.com:20240507:nL4N3HA4OG:1
2024-05-07 15:30:07.000    urn:newsml:reuters.com:20240507:nL8N3HA7QO:2
Name: storyId, dtype: string

To read a news story, **pick out one story via its storyId and display the full text** provided as HTML code.

In [50]:
storyId = news['storyId'][0]

In [51]:
from IPython.display import HTML

In [54]:
response = ld.content.news.story.Definition(storyId).get_data()
print(response.data.story.title, '\n')
HTML(response.data.story.content.html)

Tesla halts production of Model 2 to focus on Robotaxi, reports say

## Conclusions

This tutorial covers the **basic functions** of the `LSEG Data` Python wrapper package:

* `lseg.data` package
* `ld.content.symbol_conversion`
* `ld.get_data()`
* `ld.get_history()`
* `ld.news.get_headlines`

## LSEG Data Python Library Developer Resources

* [API Pages](https://developers.lseg.com/en/api-catalog) 
* [Q&A Forums](https://community.developers.refinitiv.com/index.html) 

Data Item Browser Application: Type `DIB` into Workspace Search Bar.

* [Article on Chains](https://developers.lseg.com/en/article-catalog/article/simple-chain-objects-ema-part-1)

<img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="28%" align="left" style="vertical-align: top; padding-top: 23px;">
<img src="http://hilpisch.com/tpq_logo_long.png" width="36%" align="right" style="vertical-align: top;">