----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Content - Symbol Conversion
This notebook demonstrates how to convert between different Symbology types using the LSEG Data Platform OR via LSEG Eikon/Workspace.  

#### Currently supported Symbol Types - ld.SymbolTypes enum
- ld.content.symbol_conversion.RIC => RIC
- ld.content.symbol_conversion.ISIN => IssueISIN
- ld.content.symbol_conversion.CUSIP => CUSIP
- ld.content.symbol_conversion.SEDOL => SEDOL
- ld.content.symbol_conversion.TICKER_SYMBOL => TickerSymbol
- ld.content.symbol_conversion.OA_PERM_ID => IssuerOAPermID
- ld.content.symbol_conversion.LIPPER_ID => FundClassLipperID

## Set the location of the configuration file
For ease of use, you can set various initialization parameters of the RD Library in the **_lseg-data.config.json_** configuration file - as described in the Quick Start -> Sessions example.

### One config file for the tutorials
As these tutorial Notebooks are categorised into sub-folders and to avoid the need for multiple config files, we will use the _LD_LIB_CONFIG_PATH_ environment variable to point to a single instance of the config file in the top-level ***Configuration*** folder.

Before proceeding, please **ensure you have entered your credentials** into the config file in the ***Configuration*** folder.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../../Configuration"

In [1]:
from lseg.data.content import symbol_conversion
import lseg.data as ld

## Open the default session

To open the default session ensure you have a '*lseg-data.config.json*' in the ***Configuration*** directory, populated with your credentials and specified a 'default' session in the config file

In [2]:
ld.open_session()

### Default conversion of one symbol (default input symbol type is RIC)

In [3]:
response = symbol_conversion.Definition("MSFT.O").get_data()
response.data.df

,DocumentTitle,RIC,IssueISIN,CUSIP,TickerSymbol,IssuerOAPermID
MSFT.O,"Microsoft Corp, Ordinary Share, NASDAQ Global ...",MSFT.O,US5949181045,594918104,MSFT,4295907168

### Conversion of multiple symbols

In [4]:
response = symbol_conversion.Definition(symbols=["MSFT.O", "AAPL.O", "GOOG.O", "IBM.N"]).get_data()
response.data.df

,DocumentTitle,RIC,IssueISIN,CUSIP,SEDOL,TickerSymbol,IssuerOAPermID
MSFT.O,"Microsoft Corp, Ordinary Share, NASDAQ Global ...",MSFT.O,US5949181045,594918104,<NA>,MSFT,4295907168
AAPL.O,"Apple Inc, Ordinary Share, NASDAQ Global Selec...",AAPL.O,US0378331005,037833100,<NA>,AAPL,4295905573
GOOG.O,"Alphabet Inc, Ordinary Share, Class C, NASDAQ ...",GOOG.O,US02079K1079,02079K107,<NA>,GOOG,5030853586
IBM.N,"International Business Machines Corp, Ordinary...",IBM.N,US4592001014,459200101,2005973,IBM,4295904307

### Conversion using symbol types

In [5]:
# Symbol types:
# - symbol_conversion.RIC => RIC
# - symbol_conversion.ISIN => IssueISIN
# - symbol_conversion.CUSIP => CUSIP
# - symbol_conversion.SEDOL => SEDOL
# - symbol_conversion.TICKER_SYMBOL => TickerSymbol
# - symbol_conversion.OA_PERM_ID => IssuerOAPermID
# - symbol_conversion.LIPPER_ID => FundClassLipperID

response = symbol_conversion.Definition(
    symbols=["US5949181045", "US02079K1079"],
    from_symbol_type=symbol_conversion.SymbolTypes.ISIN,
    to_symbol_types=[
        symbol_conversion.SymbolTypes.RIC,
        symbol_conversion.SymbolTypes.OA_PERM_ID
    ],
).get_data()

response.data.df

,DocumentTitle,RIC,IssuerOAPermID
US5949181045,"Microsoft Corp, Ordinary Share, NASDAQ Global ...",MSFT.O,4295907168
US02079K1079,"Alphabet Inc, Ordinary Share, Class C, NASDAQ ...",GOOG.O,5030853586

### Checking the Response Data
How to check if we got a sucessful Response and the data formats it contains

In [6]:
response = symbol_conversion.Definition(
    symbols = ["60000008", "60003513"],
    from_symbol_type = symbol_conversion.SymbolTypes.LIPPER_ID
).get_data()

In [7]:
if response.data.raw:
    display(response.data.raw)
else:
    print("Response does not contain raw data")    
# Check if the response contains a Dataframe too?
if (not response.data.df.empty):
    display(response.data.df)
else:
    print("\nResponse does not contain DataFrame")

{'Matches': {'60000008': {'DocumentTitle': 'AS SICAV I - American Focused Equity A Acc USD, Open-End Fund, USD, Luxembourg Stock Exchange',
   'RIC': '001196383X.LU',
   'IssueISIN': 'LU0011963831',
   'SEDOL': 'BPJL9R8',
   'FundClassLipperID': '60000008'},
  '60003513': {'DocumentTitle': 'JPM Japan Sustainable Equity A Acc JPY, Open-End Fund, JPY, Lipper',
   'RIC': 'LP60003513',
   'IssueISIN': 'LU0070214613',
   'SEDOL': '5408364',
   'FundClassLipperID': '60003513'}}}

,DocumentTitle,RIC,IssueISIN,SEDOL,FundClassLipperID
60000008,AS SICAV I - American Focused Equity A Acc USD...,001196383X.LU,LU0011963831,BPJL9R8,60000008
60003513,"JPM Japan Sustainable Equity A Acc JPY, Open-E...",LP60003513,LU0070214613,5408364,60003513

## Close the default session

In [8]:
ld.close_session()