----
<div style="display: flex; align-items: center;">
    <img src="https://developers.lseg.com/content/dam/devportal/icons/logo/lseg-logo.svg" width="20%" style="vertical-align: top;">
    <h1 style="margin-left: 20px;">Data Library for Python</h1>
</div>

----

## Access layer - Get data
This notebook demonstrates how to retrieve Pricing snapshots and Fundamental & Reference data using the get_data() function.

#### About the get_data function
The get_data() function allows you to retrieve pricing snapshots as well as Fundamental & Reference data via a single function call.


***get_data()*** parameters: 
- ***universe***: Single instrument or list of instruments to request
    - Type: String or list
    - Optional: No  
- ***fields***: Single field or list of fields to request
    - Type: String or list
    - Optional: Yes  
- ***parameters***: Additional parameters for Fundamental & Reference fields ("TR." fields)
    - Type: Dictionary
    - Optional: Yes  
    
**get_data()** returns a pandas.DataFrame with fields in columns and instruments as row index.  
It raises exceptions on error and when no data is available

#### Learn more

To learn more about the LSEG Data Library for Python please join the LSEG Developer Community. By [registering](https://developers.refinitiv.com/iam/register) and [logging](https://developers.refinitiv.com/content/devportal/en_us/initCookie.html) into the Refinitiv Developer Community portal you will have free access to a number of learning materials 
 on the [LSEG Developer Portal](https://developers.lseg.com/en/).

#### Getting Help and Support

If you have any questions regarding using the API, please post them on 
the [Refinitiv Data Q&A Forum](https://community.developers.refinitiv.com/spaces/321/index.html). 
The Refinitiv Developer Community will be happy to help. 

----

## Set the configuration file location
For a better ease of use, you have the option to set initialization parameters of the LSEG Data Library in the _lseg-data.config.json_ configuration file. This file must be located beside your notebook, in your user folder or in a folder defined by the _LD_LIB_CONFIG_PATH_ environment variable. The _LD_LIB_CONFIG_PATH_ environment variable is the option used by this series of examples. The following code sets this environment variable.

In [1]:
import os
os.environ["LD_LIB_CONFIG_PATH"] = "../../Configuration"

## Some Imports to start with

In [2]:
import lseg.data as ld

## Open the data session

The open_session() function creates and open sessions based on the information contained in the lseg-data.config.json configuration file. Please edit this file to set the session type and other parameters required for the session you want to open.

In [4]:
ld.open_session()

## Retrieve data

### Pricing snapshots

In [5]:
ld.get_data(
    universe=['LSEG.L', 'VOD.L'],
    fields=['BID', 'ASK']
)

  Instrument   BID    ASK
0     LSEG.L  8700   9900
1      VOD.L  68.5  70.48

### Fundamental data

In [6]:
ld.get_data(
    universe=['LSEG.L', 'VOD.L'],
    fields=['TR.Revenue']    
)

  Instrument      Revenue
0     LSEG.L   8379000000
1      VOD.L  36717000000

### Mix of pricing snapshots and fundamental data

In [7]:
ld.get_data(
    universe=['LSEG.L', 'VOD.L'], 
    fields=['BID', 'ASK', 'TR.Revenue']
)

  Instrument      Revenue   BID    ASK
0     LSEG.L   8379000000  8700   9900
1      VOD.L  36717000000  68.5  70.48

### Fundamental fields with parameters

In [8]:
ld.get_data(
    universe=['LSEG.L', 'VOD.L'],
    fields=['TR.PriceTargetMean(Source=ThomsonReuters)']
)

  Instrument  Price Target - Mean
0     LSEG.L              10580.0
1      VOD.L             87.56717

### Fundamental fields with global parameters

In [9]:
ld.get_data(
    universe=['LSEG.L', 'VOD.L'],
    fields=['TR.EV','TR.EVToSales'],
    parameters = {'SDate': '0CY', 'Curn': 'CAD'}
)

C:\Users\U6082174\AppData\Roaming\Python\Python311\site-packages\pandas\core\dtypes\cast.py:1057:RuntimeWarning: invalid value encountered in cast
C:\Users\U6082174\AppData\Roaming\Python\Python311\site-packages\pandas\core\dtypes\cast.py:1081:RuntimeWarning: invalid value encountered in cast

,Instrument,Enterprise Value (Daily Time Series),Enterprise Value To Sales (Daily Time Series Ratio)
0,LSEG.L,98359599642.303299,7.126019
1,VOD.L,108920809325.860001,2.031571

### Fundamental fields history (Not recommended - Please use get_history instead)
_**Important note:** get\_data can be used with SDate and EDate parameters to retrieve fundamental time series. However, this practice (shown in the following two examples) is not recommended because it can cause alignment issues. This is due to the nature of get\_data which was designed for retrieving current data. For time series please use get\_history()._

In [10]:
ld.get_data(
    universe=['LSEG.L', 'VOD.L'], 
    fields=['TR.Revenue.date', 'TR.Revenue'],
    parameters = {'SDate':0, 'EDate':-3}
)

  Instrument       Date      Revenue
0     LSEG.L 2023-12-31   8379000000
1     LSEG.L 2022-12-31   7743000000
2     LSEG.L 2021-12-31   6535000000
3     LSEG.L 2020-12-31   2030000000
4      VOD.L 2024-03-31  36717000000
5      VOD.L 2023-03-31  37672000000
6      VOD.L 2022-03-31  37010000000
7      VOD.L 2021-03-31  43809000000

In [11]:
ld.get_data(
    universe=['LSEG.L', 'VOD.L'], 
    fields=['TR.Revenue(SDate=0, EDate=-3).date', 'TR.Revenue(SDate=0, EDate=-3)']
)

  Instrument       Date      Revenue
0     LSEG.L 2023-12-31   8379000000
1     LSEG.L 2022-12-31   7743000000
2     LSEG.L 2021-12-31   6535000000
3     LSEG.L 2020-12-31   2030000000
4      VOD.L 2024-03-31  36717000000
5      VOD.L 2023-03-31  37672000000
6      VOD.L 2022-03-31  37010000000
7      VOD.L 2021-03-31  43809000000

### Close the session

In [12]:
ld.close_session()